In [ ]:
from google.colab import drive,auth
from google.auth import default

import gspread as gd
import pandas as pd

In [ ]:
drive.mount('/content/drive')
auth.authenticate_user()

creds,_ = default()
gc = gd.authorize(creds)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## NEW_MASTER DF

In [ ]:
JAN = gc.open('RK MASTER DATA').worksheet('JANUARI')
FEB = gc.open('RK MASTER DATA').worksheet('FEBRUARI')
MAR = gc.open('RK MASTER DATA').worksheet('MARET')
APR = gc.open('RK MASTER DATA').worksheet('APRIL')
MEI = gc.open('RK MASTER DATA').worksheet('MEI')
JUN = gc.open('RK MASTER DATA').worksheet('JUNI')
JUL = gc.open('RK MASTER DATA').worksheet('JULI')
AUG = gc.open('RK MASTER DATA').worksheet('AGUSTUS')
SEP = gc.open('RK MASTER DATA').worksheet('SEPTEMBER')
OCT = gc.open('RK MASTER DATA').worksheet('OKTOBER')
NOV = gc.open('RK MASTER DATA').worksheet('NOVEMBER')
DES = gc.open('RK MASTER DATA').worksheet('DESEMBER')

In [ ]:
JAN_df = JAN.get_all_values()
FEB_df = FEB.get_all_values()
MAR_df = MAR.get_all_values()
APR_df = APR.get_all_values()
MEI_df = MEI.get_all_values()
JUN_df = JUN.get_all_values()
JUL_df = JUL.get_all_values()
AUG_df = AUG.get_all_values()
SEP_df = SEP.get_all_values()
OCT_df = OCT.get_all_values()
NOV_df = NOV.get_all_values()
DES_df = DES.get_all_values()

In [ ]:
JANUARI = pd.DataFrame(JAN_df)
FEBRUARI = pd.DataFrame(FEB_df)
MARET = pd.DataFrame(MAR_df)
APRIL = pd.DataFrame(APR_df)
MEI = pd.DataFrame(MEI_df)
JUNI = pd.DataFrame(JUN_df)
JULI = pd.DataFrame(JUL_df)
AGUSTUS = pd.DataFrame(AUG_df)
SEPTEMBER = pd.DataFrame(SEP_df)
OKTOBER = pd.DataFrame(OCT_df)
NOVEMBER = pd.DataFrame(NOV_df)
DESEMBER = pd.DataFrame(DES_df)

In [ ]:
def process_bulan(df):
  df.columns = df.iloc[1]
  df = df.iloc[2:].reset_index(drop=True)
  return df

In [ ]:
JANUARI = process_bulan(JANUARI)
FEBRUARI = process_bulan(FEBRUARI)
MARET = process_bulan(MARET)
APRIL = process_bulan(APRIL)
MEI = process_bulan(MEI)
JUNI = process_bulan(JUNI)
JULI = process_bulan(JULI)
AGUSTUS = process_bulan(AGUSTUS)
SEPTEMBER = process_bulan(SEPTEMBER)
OKTOBER = process_bulan(OKTOBER)
NOVEMBER = process_bulan(NOVEMBER)
DESEMBER = process_bulan(DESEMBER)

In [ ]:
NEW_MASTER = pd.concat([JANUARI, FEBRUARI, MARET, APRIL, MEI, JUNI, JULI, AGUSTUS, SEPTEMBER, OKTOBER, NOVEMBER, DESEMBER])

In [ ]:
NEW_MASTER

1,KODE DONATUR,TANGGAL,NAMA DONATUR,NO REFF,DEBET,KETERANGAN,NAMA BANK,Akad Update
0,2930,1/1/2024,liburan November NANY MARYANI,BCA446.23.0225,50000,ZAKAT,BCA 446,LIBURAN
0,,2/2/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT
0,,3/3/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT
0,,4/4/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT
0,,5/5/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT
0,,6/6/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT
0,,7/7/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT
0,,8/8/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT
0,,9/9/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT
0,,10/10/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT
0,,11/11/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT
0,,12/12/2024,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1,ZAKAT,BCA 446,ZAKAT

In [ ]:
NEW_MASTER.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 0 to 0
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   KODE DONATUR  12 non-null     object
 1   TANGGAL       12 non-null     object
 2   NAMA DONATUR  12 non-null     object
 3   NO REFF       12 non-null     object
 4   DEBET         12 non-null     object
 5   KETERANGAN    12 non-null     object
 6   NAMA BANK     12 non-null     object
 7   Akad Update   12 non-null     object
dtypes: object(8)
memory usage: 864.0+ bytes

In [ ]:
NEW_MASTER.columns

Index(['KODE DONATUR', 'TANGGAL ', 'NAMA DONATUR', 'NO REFF', 'DEBET',
       'KETERANGAN', 'NAMA BANK', 'Akad Update'],
      dtype='object', name=1)

In [ ]:
NEW_MASTER = NEW_MASTER.drop(columns=['KETERANGAN'])

In [ ]:
NEW_MASTER['TANGGAL '] = pd.to_datetime(NEW_MASTER['TANGGAL '], format='%d/%m/%Y', errors='coerce')
NEW_MASTER['KODE DONATUR'] = NEW_MASTER['KODE DONATUR'].astype(str)
NEW_MASTER['DEBET'] = NEW_MASTER['DEBET'].astype(float)

In [ ]:
NEW_MASTER

1,KODE DONATUR,TANGGAL,NAMA DONATUR,NO REFF,DEBET,NAMA BANK,Akad Update
0,2930,2024-01-01,liburan November NANY MARYANI,BCA446.23.0225,50000.0,BCA 446,LIBURAN
0,,2024-02-02,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-03-03,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-04-04,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-05-05,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-06-06,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-07-07,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-08-08,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-09-09,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-10-10,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-11-11,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-12-12,Zakat Arifi 500 Ay 250 AISYAH BIDARA,BCA446.23.0244,1.0,BCA 446,ZAKAT

In [ ]:
NEW_MASTER.insert(3, 'BULAN', NEW_MASTER['TANGGAL '].dt.month)
columns_to_fill_nan = ['BULAN']
NEW_MASTER[columns_to_fill_nan] = NEW_MASTER[columns_to_fill_nan].fillna(method='ffill')
NEW_MASTER['BULAN'] = NEW_MASTER['BULAN'].astype('int')

NEW_MASTER.insert(4, 'TAHUN', NEW_MASTER['TANGGAL '].dt.year)
columns_to_fill_nan = ['TAHUN']
NEW_MASTER[columns_to_fill_nan] = NEW_MASTER[columns_to_fill_nan].fillna(method='ffill')
NEW_MASTER['TAHUN'] = NEW_MASTER['TAHUN'].astype('int')

In [ ]:
NEW_MASTER

1,KODE DONATUR,TANGGAL,NAMA DONATUR,BULAN,TAHUN,NO REFF,DEBET,NAMA BANK,Akad Update
0,2930,2024-01-01,liburan November NANY MARYANI,1,2024,BCA446.23.0225,50000.0,BCA 446,LIBURAN
0,,2024-02-02,Zakat Arifi 500 Ay 250 AISYAH BIDARA,2,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-03-03,Zakat Arifi 500 Ay 250 AISYAH BIDARA,3,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-04-04,Zakat Arifi 500 Ay 250 AISYAH BIDARA,4,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-05-05,Zakat Arifi 500 Ay 250 AISYAH BIDARA,5,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-06-06,Zakat Arifi 500 Ay 250 AISYAH BIDARA,6,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-07-07,Zakat Arifi 500 Ay 250 AISYAH BIDARA,7,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-08-08,Zakat Arifi 500 Ay 250 AISYAH BIDARA,8,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-09-09,Zakat Arifi 500 Ay 250 AISYAH BIDARA,9,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-10-10,Zakat Arifi 500 Ay 250 AISYAH BIDARA,10,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-11-11,Zakat Arifi 500 Ay 250 AISYAH BIDARA,11,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
0,,2024-12-12,Zakat Arifi 500 Ay 250 AISYAH BIDARA,12,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT

In [ ]:
mapping_bulan = {
    1: 'Januari',
    2: 'Februari',
    3: 'Maret',
    4: 'April',
    5: 'Mei',
    6: 'Juni',
    7: 'Juli',
    8: 'Agustus',
    9: 'September',
    10: 'Oktober',
    11: 'November',
    12: 'Desember'
}

# Mengubah nilai kolom 'BULAN' sesuai dengan mapping
NEW_MASTER['BULAN'] = NEW_MASTER['BULAN'].map(mapping_bulan)

In [ ]:
NEW_MASTER['KODE DONATUR'] = NEW_MASTER['KODE DONATUR'].astype(str)

In [ ]:
NEW_MASTER = NEW_MASTER.drop_duplicates()

In [ ]:
columns_to_rename = {
    'KODE DONATUR': 'KODE_DONATUR',
    'NAMA DONATUR': 'NAMA_DONATUR',
    'NO REFF': 'NO_REFF',
    'NAMA BANK': 'NAMA_BANK',
    'Akad Update': 'KETERANGAN',
}

NEW_MASTER.rename(columns=columns_to_rename, inplace=True)

In [ ]:
NEW_MASTER['KODE_DONATUR'].unique()

array(['2930', ''], dtype=object)

In [ ]:
def update_nama_donatur(row):
    if row['KODE_DONATUR'] in ['', '-', 'nan'] or pd.isna(row['KODE_DONATUR']):
        return 'Anonim'
    else:
        return row['NAMA_DONATUR']


# Menggunakan fungsi apply untuk menerapkan aturan pada setiap baris
NEW_MASTER['NAMA_DONATUR'] = NEW_MASTER.apply(update_nama_donatur, axis=1)

In [ ]:
NEW_MASTER.reset_index(drop=True, inplace=True)
NEW_MASTER

1,KODE_DONATUR,TANGGAL,NAMA_DONATUR,BULAN,TAHUN,NO_REFF,DEBET,NAMA_BANK,KETERANGAN
0,2930,2024-01-01,liburan November NANY MARYANI,Januari,2024,BCA446.23.0225,50000.0,BCA 446,LIBURAN
1,,2024-02-02,Anonim,Februari,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
2,,2024-03-03,Anonim,Maret,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
3,,2024-04-04,Anonim,April,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
4,,2024-05-05,Anonim,Mei,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
5,,2024-06-06,Anonim,Juni,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
6,,2024-07-07,Anonim,Juli,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
7,,2024-08-08,Anonim,Agustus,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
8,,2024-09-09,Anonim,September,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
9,,2024-10-10,Anonim,Oktober,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
10,,2024-11-11,Anonim,November,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT
11,,2024-12-12,Anonim,Desember,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT

In [ ]:
master = gc.open('RK MASTER DATA').worksheet('MASTER DATA.')
db_individu = gc.open('RK MASTER DATA').worksheet('DB INDIVIDU')
db_nonindividu = gc.open('RK MASTER DATA').worksheet('DB NON INDIVIDU')
con_individu = gc.open('RK MASTER DATA').worksheet('CONTROL INDIVIDU.')
con_nonindividu = gc.open('RK MASTER DATA').worksheet('CONTROL NON INDIVIDU.')
con_produk = gc.open('RK MASTER DATA').worksheet('CONTROL PRODUK.')
con_segment = gc.open('RK MASTER DATA').worksheet('CONTROL SEGMENT.')

In [ ]:
master_df = master.get_all_values()
db_individu_df = db_individu.get_all_values()
db_nonindividu_df = db_nonindividu.get_all_values()
individu_df = con_individu.get_all_values()
nonindividu_df = con_nonindividu.get_all_values()
produk_df = con_produk.get_all_values()
segment_df = con_segment.get_all_values()

In [ ]:
master_data = pd.DataFrame(master_df)
individu = pd.DataFrame(db_individu_df)
non_individu = pd.DataFrame(db_nonindividu_df)
con_individu_df = pd.DataFrame(individu_df)
con_non_individu_df = pd.DataFrame(nonindividu_df)
con_produk_df = pd.DataFrame(produk_df)
con_segment_df = pd.DataFrame(segment_df)

In [ ]:
def process_df(df):
  df.columns = df.iloc[0]
  df = df.iloc[1:].reset_index(drop=True)
  return df

In [ ]:
master_data = process_df(master_data)
individu = process_df(individu)
con_individu_df = process_df(con_individu_df)
con_non_individu_df = process_df(con_non_individu_df)
con_produk_df = process_df(con_produk_df)
con_segment_df = process_df(con_segment_df)

In [ ]:
master_data

,KODE_DONATUR,TANGGAL,BULAN,TAHUN,NAMA_DONATUR,NO_REFF,DEBET,KETERANGAN,NAMA_BANK,BASE_DONATUR,STATUS,BULAN_NO
0,nan,2019-01-01 0:00:00,Januari,2019,Anonim,BNIS945.19.0001,50000,INFAQ,BNIS 945,Donatur Baru,Lain-Lain,1
1,nan,2019-01-01 0:00:00,Januari,2019,Anonim,BNIS945.19.0002,115000,INFAQ,BNIS 945,Donatur Baru,Lain-Lain,1
2,nan,2019-01-01 0:00:00,Januari,2019,Anonim,BNIS945.19.0003,250007,INFAQ,BNIS 945,Donatur Baru,Lain-Lain,1
3,nan,2019-01-01 0:00:00,Januari,2019,Anonim,BNIS945.19.0004,2000,INFAQ,BNIS 945,Donatur Baru,Lain-Lain,1
4,nan,2019-01-01 0:00:00,Januari,2019,Anonim,BNIS945.19.0005,100,INFAQ,BNIS 945,Donatur Baru,Lain-Lain,1
...,...,...,...,...,...,...,...,...,...,...,...,...
93298,2424,2023-11-02 0:00:00,November,2023,Anonim,NIASR6.23.0107,500000,SP,CIMB R6,Umum,tetap,11
93299,2424,2023-11-02 0:00:00,November,2023,Anonim,NIASR6.23.0108,38000,SP,CIMB R6,Umum,tetap,11
93300,nan,2023-11-06 0:00:00,November,2023,Anonim,BSI572.23.0018,174600000,INFAQ,BSI 572,Donatur Baru,Lain-Lain,11
93301,I19,2023-11-08 0:00:00,November,2023,Anonim,KB.23.0029,2000000,SP,Cash on Hand,Institusi,Aktif,11
93302,3841,2023-11-09 0:00:00,November,2023,Anonim,BSI602.23.0070,50000,LAIN-LAIN,BSI 602,Umum,tetap,11

In [ ]:
individu['NAMA_DONATUR'] = individu['NAMA_DONATUR'].str.title()

In [ ]:
non_individu.columns = non_individu.iloc[2]
non_individu = non_individu.iloc[3:].reset_index(drop=True)

In [ ]:
non_individu.tail(50)

2   KODE_DONATUR              NAMA_DONATUR
31          Kode                      Nama
32            P1       RK Management & Con
33            P2                    Loccus
34            P3                       FDP
35            P4           Project Sekolah
36            P5               STB Premium
37            P6         Pesantren Virtual
38            P7               Ngabuburead
39            P8  Post College Exploration
40            P9            Cerita Menikah
41           P10              STB Beasiswa
42           P11         STB Focus English
43           P12               STB Membaca
44           P13                  Lapak RK
45           P14               STB Digital
46           P15                      MPM
47           P16   Super Mentor Laznas BSM
48           P17
49           P18
50           P19
51           P20
52           P21
53           P22
54           P23
55         TOTAL
56
57     LAIN-LAIN
58          Kode                      Nama
59            L1                   Titipan
60            L2                      Sewa
61            L3                  Memorial
62            L4        Bagi Hasil & Bunga
63            L5                      NAMA
64            L6                    Qurban
65            L7                       NLC
66            L8
67            L9
68           L10
69
70  WAKAF ASRAMA
71          Kode                      Nama
72            W1           Wakaf Asrama R1
73            W2           Wakaf Asrama R2
74            W3           Wakaf Asrama R3
75            W4           Wakaf Asrama R4
76            W5           Wakaf Asrama R5
77            W6           Wakaf Asrama R6
78            W7           Wakaf Asrama R7
79            W8           Wakaf Asrama R8
80            W9           Wakaf Asrama R9

In [ ]:
rows_to_delete = [28, 29, 30, 31, 55, 56, 57, 58, 69, 70, 71]
non_individu = non_individu.drop(labels=rows_to_delete).reset_index(drop=True)

non_individu['KODE_DONATUR'] = non_individu['KODE_DONATUR'].astype(str)

In [ ]:
non_individu['BASE_DONATUR'] = "Lain-Lain"
non_individu.loc[non_individu['KODE_DONATUR'].str.contains('I'), 'BASE_DONATUR'] = "Institusi"

In [ ]:
non_individu

2  KODE_DONATUR            NAMA_DONATUR BASE_DONATUR
0            I1                     MTT    Institusi
1            I2             ZIS Indosat    Institusi
2            I3  LAZ Al Hakim SUCOFINDO    Institusi
3            I4                TIKI JNE    Institusi
4            I5                   MEDCO    Institusi
..          ...                     ...          ...
65           W5         Wakaf Asrama R5    Lain-Lain
66           W6         Wakaf Asrama R6    Lain-Lain
67           W7         Wakaf Asrama R7    Lain-Lain
68           W8         Wakaf Asrama R8    Lain-Lain
69           W9         Wakaf Asrama R9    Lain-Lain

[70 rows x 3 columns]

## DATA DONATUR

In [ ]:
data_Donatur = pd.concat([individu, non_individu])

In [ ]:
data_Donatur

,KODE_DONATUR,NAMA_DONATUR,GELAR_DEPAN,GELAR_BELAKANG,GENDER,BASE_DONATUR,KETERANGAN
0,1,Abdi Nugroho,,,Laki-laki,Alumni,R1 A1
1,2,Ahadiyat,,,Laki-laki,Alumni,R1 A1
2,3,Ahmad Hidayatullah,,,Laki-laki,Alumni,R1 A1
3,4,Alief Aulia Rezza,,,Laki-laki,Alumni,R1 A1
4,5,Aresto Yudo Sudjono,,,Laki-laki,Alumni,R1 A1
...,...,...,...,...,...,...,...
65,W5,Wakaf Asrama R5,NaN,NaN,NaN,Lain-Lain,NaN
66,W6,Wakaf Asrama R6,NaN,NaN,NaN,Lain-Lain,NaN
67,W7,Wakaf Asrama R7,NaN,NaN,NaN,Lain-Lain,NaN
68,W8,Wakaf Asrama R8,NaN,NaN,NaN,Lain-Lain,NaN
69,W9,Wakaf Asrama R9,NaN,NaN,NaN,Lain-Lain,NaN

In [ ]:
merged_data = pd.merge(NEW_MASTER, data_Donatur[['KODE_DONATUR', 'NAMA_DONATUR','BASE_DONATUR']], on='KODE_DONATUR', how='left')

In [ ]:
merged_data

,KODE_DONATUR,TANGGAL,NAMA_DONATUR_x,BULAN,TAHUN,NO_REFF,DEBET,NAMA_BANK,KETERANGAN,NAMA_DONATUR_y,BASE_DONATUR
0,2930,2024-01-01,liburan November NANY MARYANI,Januari,2024,BCA446.23.0225,50000.0,BCA 446,LIBURAN,Nany Maryani,Non Alumni
1,,2024-02-02,Anonim,Februari,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN
2,,2024-03-03,Anonim,Maret,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN
3,,2024-04-04,Anonim,April,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN
4,,2024-05-05,Anonim,Mei,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN
5,,2024-06-06,Anonim,Juni,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN
6,,2024-07-07,Anonim,Juli,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN
7,,2024-08-08,Anonim,Agustus,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN
8,,2024-09-09,Anonim,September,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN
9,,2024-10-10,Anonim,Oktober,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN
10,,2024-11-11,Anonim,November,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN
11,,2024-12-12,Anonim,Desember,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,NaN,NaN

In [ ]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12 entries, 0 to 11
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   KODE_DONATUR    12 non-null     object
 1   TANGGAL         12 non-null     datetime64[ns]
 2   NAMA_DONATUR_x  12 non-null     object
 3   BULAN           12 non-null     object
 4   TAHUN           12 non-null     int64
 5   NO_REFF         12 non-null     object
 6   DEBET           12 non-null     float64
 7   NAMA_BANK       12 non-null     object
 8   KETERANGAN      12 non-null     object
 9   NAMA_DONATUR_y  1 non-null      object
 10  BASE_DONATUR    1 non-null      object
dtypes: datetime64[ns](1), float64(1), int64(1), object(8)
memory usage: 1.1+ KB

In [ ]:
def update_nama_donatur(row):
    if row['KODE_DONATUR'] in ['', '-', 'nan'] or pd.isna(row['KODE_DONATUR']):
        return 'Anonim'
    else:
        return row['NAMA_DONATUR_y']

def update_base_donatur(row):
    if row['KODE_DONATUR'] in ['', '-', 'nan'] or pd.isna(row['KODE_DONATUR']):
        return 'Donatur Baru'
    else:
        return row['BASE_DONATUR']

merged_data['NAMA_DONATUR_y'] = merged_data.apply(update_nama_donatur, axis=1)
merged_data['BASE_DONATUR'] = merged_data.apply(update_base_donatur, axis=1)

In [ ]:
merged_data

,KODE_DONATUR,TANGGAL,NAMA_DONATUR_x,BULAN,TAHUN,NO_REFF,DEBET,NAMA_BANK,KETERANGAN,NAMA_DONATUR_y,BASE_DONATUR
0,2930,2024-01-01,liburan November NANY MARYANI,Januari,2024,BCA446.23.0225,50000.0,BCA 446,LIBURAN,Nany Maryani,Non Alumni
1,,2024-02-02,Anonim,Februari,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru
2,,2024-03-03,Anonim,Maret,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru
3,,2024-04-04,Anonim,April,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru
4,,2024-05-05,Anonim,Mei,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru
5,,2024-06-06,Anonim,Juni,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru
6,,2024-07-07,Anonim,Juli,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru
7,,2024-08-08,Anonim,Agustus,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru
8,,2024-09-09,Anonim,September,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru
9,,2024-10-10,Anonim,Oktober,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru
10,,2024-11-11,Anonim,November,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru
11,,2024-12-12,Anonim,Desember,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Anonim,Donatur Baru

In [ ]:
merged_data['KODE_DONATUR'].unique()

array(['2930', ''], dtype=object)

In [ ]:
merged_data.reset_index(drop=True, inplace=True)

In [ ]:
NEW_MASTER['NAMA_DONATUR'] = merged_data['NAMA_DONATUR_y']
NEW_MASTER['BASE_DONATUR'] = merged_data['BASE_DONATUR']

In [ ]:
NEW_MASTER = NEW_MASTER.rename(columns={'TANGGAL ': 'TANGGAL'})

In [ ]:
NEW_MASTER['TANGGAL'] = pd.to_datetime(NEW_MASTER['TANGGAL']).dt.strftime('%d/%m/%Y')

In [ ]:
NEW_MASTER

1,KODE_DONATUR,TANGGAL,NAMA_DONATUR,BULAN,TAHUN,NO_REFF,DEBET,NAMA_BANK,KETERANGAN,BASE_DONATUR
0,2930,01/01/2024,Nany Maryani,Januari,2024,BCA446.23.0225,50000.0,BCA 446,LIBURAN,Non Alumni
1,,02/02/2024,Anonim,Februari,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru
2,,03/03/2024,Anonim,Maret,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru
3,,04/04/2024,Anonim,April,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru
4,,05/05/2024,Anonim,Mei,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru
5,,06/06/2024,Anonim,Juni,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru
6,,07/07/2024,Anonim,Juli,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru
7,,08/08/2024,Anonim,Agustus,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru
8,,09/09/2024,Anonim,September,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru
9,,10/10/2024,Anonim,Oktober,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru
10,,11/11/2024,Anonim,November,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru
11,,12/12/2024,Anonim,Desember,2024,BCA446.23.0244,1.0,BCA 446,ZAKAT,Donatur Baru

In [ ]:
master_data

,KODE_DONATUR,TANGGAL,BULAN,TAHUN,NAMA_DONATUR,NO_REFF,DEBET,KETERANGAN,NAMA_BANK,BASE_DONATUR,STATUS,BULAN_NO
0,nan,2019-01-01 0:00:00,Januari,2019,Anonim,BNIS945.19.0001,50000,INFAQ,BNIS 945,Donatur Baru,Lain-Lain,1
1,nan,2019-01-01 0:00:00,Januari,2019,Anonim,BNIS945.19.0002,115000,INFAQ,BNIS 945,Donatur Baru,Lain-Lain,1
2,nan,2019-01-01 0:00:00,Januari,2019,Anonim,BNIS945.19.0003,250007,INFAQ,BNIS 945,Donatur Baru,Lain-Lain,1
3,nan,2019-01-01 0:00:00,Januari,2019,Anonim,BNIS945.19.0004,2000,INFAQ,BNIS 945,Donatur Baru,Lain-Lain,1
4,nan,2019-01-01 0:00:00,Januari,2019,Anonim,BNIS945.19.0005,100,INFAQ,BNIS 945,Donatur Baru,Lain-Lain,1
...,...,...,...,...,...,...,...,...,...,...,...,...
93298,2424,2023-11-02 0:00:00,November,2023,Anonim,NIASR6.23.0107,500000,SP,CIMB R6,Umum,tetap,11
93299,2424,2023-11-02 0:00:00,November,2023,Anonim,NIASR6.23.0108,38000,SP,CIMB R6,Umum,tetap,11
93300,nan,2023-11-06 0:00:00,November,2023,Anonim,BSI572.23.0018,174600000,INFAQ,BSI 572,Donatur Baru,Lain-Lain,11
93301,I19,2023-11-08 0:00:00,November,2023,Anonim,KB.23.0029,2000000,SP,Cash on Hand,Institusi,Aktif,11
93302,3841,2023-11-09 0:00:00,November,2023,Anonim,BSI602.23.0070,50000,LAIN-LAIN,BSI 602,Umum,tetap,11

In [ ]:
master_data = pd.concat([master_data, NEW_MASTER], ignore_index=True)
master_data.tail(15)

,KODE_DONATUR,TANGGAL,BULAN,TAHUN,NAMA_DONATUR,NO_REFF,DEBET,KETERANGAN,NAMA_BANK,BASE_DONATUR,STATUS,BULAN_NO
93300,nan,2023-11-06 0:00:00,November,2023,Anonim,BSI572.23.0018,174600000,INFAQ,BSI 572,Donatur Baru,Lain-Lain,11
93301,I19,2023-11-08 0:00:00,November,2023,Anonim,KB.23.0029,2000000,SP,Cash on Hand,Institusi,Aktif,11
93302,3841,2023-11-09 0:00:00,November,2023,Anonim,BSI602.23.0070,50000,LAIN-LAIN,BSI 602,Umum,tetap,11
93303,2930,01/01/2024,Januari,2024,Nany Maryani,BCA446.23.0225,50000.0,LIBURAN,BCA 446,Non Alumni,NaN,NaN
93304,,02/02/2024,Februari,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN
93305,,03/03/2024,Maret,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN
93306,,04/04/2024,April,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN
93307,,05/05/2024,Mei,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN
93308,,06/06/2024,Juni,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN
93309,,07/07/2024,Juli,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN
93310,,08/08/2024,Agustus,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN
93311,,09/09/2024,September,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN
93312,,10/10/2024,Oktober,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN
93313,,11/11/2024,November,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN
93314,,12/12/2024,Desember,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN

In [ ]:
replace_dict = {
    'Donatur Regional': 'Umum',
    'Jejaring EP': 'Umum',
    'STT NF': 'Umum',
    'Dewan Pembina': 'Pembina',
    'EP RK': 'Umum',
    'INSTITUSI': 'Institusi',
    'Orangtua Alumni': 'Orang Tua',
    'Orangtua Peserta': 'Orang Tua',
    'Pembicara RK': 'Umum',
    'Lentras': 'Umum',
    'BKB NF': 'Umum',
    '-': 'Donatur Baru',
    'ER RK': 'Umum',
    'LAIN-LAIN': 'Lain-Lain',
    'PAW RK': 'Umum',
    'Peserta X': 'Umum',
    'Orang Tua Peserta': 'Orang Tua',
    'FAMIHUB': 'Umum',
    'RKA': 'Umum',
    'ORTU': 'Orang Tua',
    'LIBURAN': 'Umum',
    'Pengurus Pusat': 'Umum',
    'Non Alumni': 'Umum',
}

master_data['BASE_DONATUR'] = master_data['BASE_DONATUR'].replace(replace_dict).fillna('Donatur Baru')

In [ ]:
master_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93315 entries, 0 to 93314
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   KODE_DONATUR  93315 non-null  object
 1   TANGGAL       93315 non-null  object
 2   BULAN         93315 non-null  object
 3   TAHUN         93315 non-null  object
 4   NAMA_DONATUR  93315 non-null  object
 5   NO_REFF       93315 non-null  object
 6   DEBET         93315 non-null  object
 7   KETERANGAN    93315 non-null  object
 8   NAMA_BANK     93315 non-null  object
 9   BASE_DONATUR  93315 non-null  object
 10  STATUS        93303 non-null  object
 11  BULAN_NO      93303 non-null  object
dtypes: object(12)
memory usage: 8.5+ MB

In [ ]:
master_data['TANGGAL'] = pd.to_datetime(master_data['TANGGAL']).dt.strftime('%d/%m/%Y')
master_data['DEBET'] = master_data['DEBET'].astype(float)

In [ ]:
control = master_data.pivot_table(index='KODE_DONATUR', columns='BULAN', values='DEBET', aggfunc={'DEBET': ['count', 'sum']})
#control = master_data.pivot_table(index=['KODE_DONATUR'], columns='BULAN', values='DEBET', aggfunc=['count','sum'])
control.head(20)

               count                                                         \
BULAN        Agustus April Desember Februari Januari  Juli  Juni Maret  Mei
KODE_DONATUR
                 1.0   1.0      1.0      1.0     NaN   1.0   1.0   1.0  1.0
               801.0   NaN      1.0      1.0     NaN   NaN   NaN   NaN  NaN
-                NaN   NaN      NaN      NaN     NaN   NaN   NaN   NaN  NaN
1                NaN   NaN      NaN      NaN     1.0   NaN   NaN   1.0  NaN
10               4.0  11.0      2.0      4.0     5.0   3.0   4.0   4.0  6.0
100             10.0  11.0      7.0     10.0    10.0  10.0  10.0  11.0  8.0
1001             NaN   5.0      2.0      4.0     1.0   2.0   NaN   NaN  2.0
1004             NaN   NaN      NaN      1.0     NaN   NaN   NaN   NaN  NaN
1006             NaN   NaN      NaN      1.0     NaN   NaN   NaN   NaN  NaN
1007             2.0   4.0      3.0      2.0     3.0   1.0   3.0   2.0  4.0
1008             4.0   2.0      4.0      2.0     5.0   3.0   4.0   3.0  3.0
1009             NaN   NaN      NaN      NaN     1.0   NaN   NaN   1.0  NaN
101              2.0   5.0      4.0      4.0     5.0   3.0   4.0   5.0  1.0
1010             NaN   NaN      NaN      NaN     NaN   NaN   1.0   NaN  NaN
1012             1.0   NaN      2.0      1.0     2.0   1.0   NaN   1.0  1.0
1013             1.0   2.0      NaN      1.0     2.0   1.0   1.0   2.0  1.0
1014             1.0   3.0      NaN      2.0     2.0   1.0   NaN   4.0  3.0
1015             3.0   3.0      4.0      1.0     2.0   2.0   4.0   2.0  1.0
1016             1.0   1.0      2.0      1.0     2.0   NaN   2.0   1.0  1.0
1017             NaN   2.0      NaN      NaN     NaN   NaN   1.0   NaN  NaN

                       ...        sum                                   \
BULAN        November  ...   Desember   Februari    Januari       Juli
KODE_DONATUR           ...
                  1.0  ...        1.0        1.0        NaN        1.0
                  1.0  ...  5550000.0        1.0        NaN        NaN
-                 NaN  ...        NaN        NaN        NaN        NaN
1                 NaN  ...        NaN        NaN   250000.0        NaN
10                2.0  ...   500661.0  1001322.0  2001322.0  1250661.0
100               9.0  ...  2000282.0  2500470.0  3000470.0  2500470.0
1001              NaN  ...  1500000.0  3900000.0   500000.0  1250000.0
1004              NaN  ...        NaN   100000.0        NaN        NaN
1006              NaN  ...        NaN  1000000.0        NaN        NaN
1007              4.0  ...   550000.0   650000.0   700000.0   400000.0
1008              3.0  ...   350000.0   225000.0   450000.0   225000.0
1009              NaN  ...        NaN        NaN   300000.0        NaN
101               3.0  ...  3500000.0  3000000.0  4000000.0  2000000.0
1010              NaN  ...        NaN        NaN        NaN        NaN
1012              1.0  ...   125000.0   100000.0   200000.0    75000.0
1013              1.0  ...        NaN   125000.0   200000.0    75000.0
1014              2.0  ...        NaN   325000.0   200000.0    75000.0
1015              4.0  ...   625000.0   100000.0   200000.0   325000.0
1016              2.0  ...   125000.0   250000.0   325000.0        NaN
1017              1.0  ...        NaN        NaN        NaN        NaN


BULAN              Juni      Maret        Mei   November    Oktober  September
KODE_DONATUR
                    1.0        1.0        1.0        1.0        1.0        1.0
                    NaN        NaN        NaN    20000.0        NaN   860000.0
-                   NaN        NaN        NaN        NaN  1370000.0        NaN
1                   NaN   500000.0        NaN        NaN        NaN        NaN
10            1001322.0  1001322.0  7001322.0   500661.0  1000661.0  1001322.0
100           2500470.0  4500376.0  2000376.0  2500376.0  2500376.0  2500470.0
1001                NaN        NaN  1150000.0        NaN        NaN  3000000.0
1004                NaN        NaN        NaN        NaN        NaN        NaN
1006                NaN        NaN        NaN        NaN        NaN        NaN
1007          1000000.0   650000.0  1100000.0  1450000.0   750000.0   950000.0
1008           435000.0   300000.0   475000.0   250000.0   200000.0   187500.0
1009                NaN   125000.0        NaN        NaN        NaN        NaN
101           3000000.0  4000000.0  1000000.0  2000000.0  4000000.0  2009000.0
1010            20000.0        NaN        NaN        NaN        NaN        NaN
1012                NaN    75000.0   400000.0    87500.0   150000.0    87500.0
1013           300000.0   150000.0    75000.0    87500.0        NaN    75000.0
1014                NaN   500000.0   575000.0    97500.0        NaN    75000.0
1015           650000.0   325000.0   300000.0   687500.0   500000.0   587500.0
1016           500000.0    75000.0   300000.0   587500.0        NaN   250000.0
1017           100000.0        NaN        NaN     2000.0    50000.0        NaN

[20 rows x 24 columns]

In [ ]:
control.columns = ['_'.join(col).strip() if col[1] else col[0] for col in control.columns]
control = control.reset_index()
control.head()

,KODE_DONATUR,count_Agustus,count_April,count_Desember,count_Februari,count_Januari,count_Juli,count_Juni,count_Maret,count_Mei,...,sum_Desember,sum_Februari,sum_Januari,sum_Juli,sum_Juni,sum_Maret,sum_Mei,sum_November,sum_Oktober,sum_September
0,,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,...,1.0,1.0,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,,801.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,5550000.0,1.0,NaN,NaN,NaN,NaN,NaN,20000.0,NaN,860000.0
2,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1370000.0,NaN
3,1,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,...,NaN,NaN,250000.0,NaN,NaN,500000.0,NaN,NaN,NaN,NaN
4,10,4.0,11.0,2.0,4.0,5.0,3.0,4.0,4.0,6.0,...,500661.0,1001322.0,2001322.0,1250661.0,1001322.0,1001322.0,7001322.0,500661.0,1000661.0,1001322.0

In [ ]:
control.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3215 entries, 0 to 3214
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   KODE_DONATUR     3215 non-null   object
 1   count_Agustus    769 non-null    float64
 2   count_April      1763 non-null   float64
 3   count_Desember   629 non-null    float64
 4   count_Februari   947 non-null    float64
 5   count_Januari    1119 non-null   float64
 6   count_Juli       875 non-null    float64
 7   count_Juni       839 non-null    float64
 8   count_Maret      1041 non-null   float64
 9   count_Mei        1295 non-null   float64
 10  count_November   889 non-null    float64
 11  count_Oktober    932 non-null    float64
 12  count_September  953 non-null    float64
 13  sum_Agustus      769 non-null    float64
 14  sum_April        1763 non-null   float64
 15  sum_Desember     629 non-null    float64
 16  sum_Februari     947 non-null    float64
 17  sum_Januari      1119 non-null   float64
 18  sum_Juli         875 non-null    float64
 19  sum_Juni         839 non-null    float64
 20  sum_Maret        1041 non-null   float64
 21  sum_Mei          1295 non-null   float64
 22  sum_November     889 non-null    float64
 23  sum_Oktober      932 non-null    float64
 24  sum_September    953 non-null    float64
dtypes: float64(24), object(1)
memory usage: 628.1+ KB

In [ ]:
#columns_to_convert = ['sum_Agustus', 'sum_April', 'sum_Desember', 'sum_Februari', 'sum_Januari',
#                       'sum_Juli', 'sum_Juni', 'sum_Maret', 'sum_Mei', 'sum_November',
#                       'sum_Oktober', 'sum_September']


#control[columns_to_convert] = control[columns_to_convert].apply(pd.to_numeric, errors='coerce')

In [ ]:
control['cnt_donasi'] = control.iloc[:, 1:13].sum(axis=1)
control['Donation Rate'] = control.iloc[:, 1:13].sum(axis=1) / len(control.iloc[:, 1:13].columns)
control['Total Donation'] = control.iloc[:, 13:25].sum(axis=1)
control.head()

,KODE_DONATUR,count_Agustus,count_April,count_Desember,count_Februari,count_Januari,count_Juli,count_Juni,count_Maret,count_Mei,...,sum_Juli,sum_Juni,sum_Maret,sum_Mei,sum_November,sum_Oktober,sum_September,cnt_donasi,Donation Rate,Total Donation
0,,1.0,1.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,11.0,0.916667,11.0
1,,801.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20000.0,NaN,860000.0,810.0,67.500000,112970113.0
2,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1370000.0,NaN,2.0,0.166667,1370000.0
3,1,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,...,NaN,NaN,500000.0,NaN,NaN,NaN,NaN,2.0,0.166667,750000.0
4,10,4.0,11.0,2.0,4.0,5.0,3.0,4.0,4.0,6.0,...,1250661.0,1001322.0,1001322.0,7001322.0,500661.0,1000661.0,1001322.0,52.0,4.333333,23063220.0

In [ ]:
db_individu_tmp = individu.drop(['GELAR_DEPAN', 'GELAR_BELAKANG'], axis=1)
control_tmp = control[['KODE_DONATUR','cnt_donasi','Donation Rate','Total Donation']]
df_individu = db_individu_tmp.merge(control_tmp, left_on=['KODE_DONATUR'], right_on=['KODE_DONATUR'], how='left', suffixes=['_db_individu', '_control'])


df_non_individu = non_individu.drop_duplicates(subset=['NAMA_DONATUR'])
control_tmp = control[['KODE_DONATUR','cnt_donasi','Donation Rate','Total Donation']]
df_non_individu = non_individu.merge(control_tmp, left_on=['KODE_DONATUR'], right_on=['KODE_DONATUR'], how='left', suffixes=['_db_non_individu', '_control'])

In [ ]:
df_individu

,KODE_DONATUR,NAMA_DONATUR,GENDER,BASE_DONATUR,KETERANGAN,cnt_donasi,Donation Rate,Total Donation
0,1,Abdi Nugroho,Laki-laki,Alumni,R1 A1,2.0,0.166667,750000.0
1,2,Ahadiyat,Laki-laki,Alumni,R1 A1,47.0,3.916667,51055000.0
2,3,Ahmad Hidayatullah,Laki-laki,Alumni,R1 A1,18.0,1.500000,8000000.0
3,4,Alief Aulia Rezza,Laki-laki,Alumni,R1 A1,12.0,1.000000,11575835.0
4,5,Aresto Yudo Sudjono,Laki-laki,Alumni,R1 A1,13.0,1.083333,12400166.0
...,...,...,...,...,...,...,...,...
4674,4706,Mimah Candra Devi,,,,NaN,NaN,NaN
4675,4707,Muhamad Hasan Asyari,,,,2.0,0.166667,450000.0
4676,4708,Hannifah Restu Fau,,,,NaN,NaN,NaN
4677,4709,Mitri Rahmawati,,,,3.0,0.250000,450000.0
4678,4710,Andri Yanti,,,,1.0,0.083333,100000.0

In [ ]:
df_individu['STATUS'] = 'donatur baru'

# Check conditions and update 'status'
df_individu.loc[df_individu['cnt_donasi'] > 0, 'STATUS'] = 'potensial'
df_individu.loc[df_individu['cnt_donasi'] > 5, 'STATUS'] = 'tetap'
df_individu.loc[(df_individu['cnt_donasi'] > 5) & (df_individu['Total Donation'] > 17999999), 'STATUS'] = 'prioritas'

In [ ]:
df_individu

,KODE_DONATUR,NAMA_DONATUR,GENDER,BASE_DONATUR,KETERANGAN,cnt_donasi,Donation Rate,Total Donation,STATUS
0,1,Abdi Nugroho,Laki-laki,Alumni,R1 A1,2.0,0.166667,750000.0,potensial
1,2,Ahadiyat,Laki-laki,Alumni,R1 A1,47.0,3.916667,51055000.0,prioritas
2,3,Ahmad Hidayatullah,Laki-laki,Alumni,R1 A1,18.0,1.500000,8000000.0,tetap
3,4,Alief Aulia Rezza,Laki-laki,Alumni,R1 A1,12.0,1.000000,11575835.0,tetap
4,5,Aresto Yudo Sudjono,Laki-laki,Alumni,R1 A1,13.0,1.083333,12400166.0,tetap
...,...,...,...,...,...,...,...,...,...
4674,4706,Mimah Candra Devi,,,,NaN,NaN,NaN,donatur baru
4675,4707,Muhamad Hasan Asyari,,,,2.0,0.166667,450000.0,potensial
4676,4708,Hannifah Restu Fau,,,,NaN,NaN,NaN,donatur baru
4677,4709,Mitri Rahmawati,,,,3.0,0.250000,450000.0,potensial
4678,4710,Andri Yanti,,,,1.0,0.083333,100000.0,potensial

In [ ]:
df_non_individu['STATUS'] = 'Tidak Aktif'

# Check conditions and update 'status'
df_non_individu.loc[df_non_individu['cnt_donasi'] > 0, 'STATUS'] = 'Aktif'
df_non_individu

,KODE_DONATUR,NAMA_DONATUR,BASE_DONATUR,cnt_donasi,Donation Rate,Total Donation,STATUS
0,I1,MTT,Institusi,12.0,1.000000,4.020000e+08,Aktif
1,I2,ZIS Indosat,Institusi,32.0,2.666667,6.272500e+08,Aktif
2,I3,LAZ Al Hakim SUCOFINDO,Institusi,5.0,0.416667,5.000000e+07,Aktif
3,I4,TIKI JNE,Institusi,52.0,4.333333,5.200000e+08,Aktif
4,I5,MEDCO,Institusi,38.0,3.166667,1.420000e+09,Aktif
...,...,...,...,...,...,...,...
65,W5,Wakaf Asrama R5,Lain-Lain,30.0,2.500000,6.081827e+07,Aktif
66,W6,Wakaf Asrama R6,Lain-Lain,NaN,NaN,NaN,Tidak Aktif
67,W7,Wakaf Asrama R7,Lain-Lain,NaN,NaN,NaN,Tidak Aktif
68,W8,Wakaf Asrama R8,Lain-Lain,NaN,NaN,NaN,Tidak Aktif
69,W9,Wakaf Asrama R9,Lain-Lain,NaN,NaN,NaN,Tidak Aktif

In [ ]:
df_individu.columns

Index(['KODE_DONATUR', 'NAMA_DONATUR', 'GENDER', 'BASE_DONATUR', 'KETERANGAN',
       'cnt_donasi', 'Donation Rate', 'Total Donation', 'STATUS'],
      dtype='object')

In [ ]:
df_non_individu.columns

Index(['KODE_DONATUR', 'NAMA_DONATUR', 'BASE_DONATUR', 'cnt_donasi',
       'Donation Rate', 'Total Donation', 'STATUS'],
      dtype='object')

In [ ]:
concat_data_donatur = pd.concat([df_individu, df_non_individu], ignore_index=True)
concat_data_donatur

,KODE_DONATUR,NAMA_DONATUR,GENDER,BASE_DONATUR,KETERANGAN,cnt_donasi,Donation Rate,Total Donation,STATUS
0,1,Abdi Nugroho,Laki-laki,Alumni,R1 A1,2.0,0.166667,750000.0,potensial
1,2,Ahadiyat,Laki-laki,Alumni,R1 A1,47.0,3.916667,51055000.0,prioritas
2,3,Ahmad Hidayatullah,Laki-laki,Alumni,R1 A1,18.0,1.500000,8000000.0,tetap
3,4,Alief Aulia Rezza,Laki-laki,Alumni,R1 A1,12.0,1.000000,11575835.0,tetap
4,5,Aresto Yudo Sudjono,Laki-laki,Alumni,R1 A1,13.0,1.083333,12400166.0,tetap
...,...,...,...,...,...,...,...,...,...
4744,W5,Wakaf Asrama R5,NaN,Lain-Lain,NaN,30.0,2.500000,60818273.0,Aktif
4745,W6,Wakaf Asrama R6,NaN,Lain-Lain,NaN,NaN,NaN,NaN,Tidak Aktif
4746,W7,Wakaf Asrama R7,NaN,Lain-Lain,NaN,NaN,NaN,NaN,Tidak Aktif
4747,W8,Wakaf Asrama R8,NaN,Lain-Lain,NaN,NaN,NaN,NaN,Tidak Aktif
4748,W9,Wakaf Asrama R9,NaN,Lain-Lain,NaN,NaN,NaN,NaN,Tidak Aktif

In [ ]:
merge_data = pd.merge(master_data, concat_data_donatur[['KODE_DONATUR', 'STATUS']], on='KODE_DONATUR', how='left')
merge_data.tail(15)

,KODE_DONATUR,TANGGAL,BULAN,TAHUN,NAMA_DONATUR,NO_REFF,DEBET,KETERANGAN,NAMA_BANK,BASE_DONATUR,STATUS_x,BULAN_NO,STATUS_y
93300,nan,06/11/2023,November,2023,Anonim,BSI572.23.0018,174600000.0,INFAQ,BSI 572,Donatur Baru,Lain-Lain,11,NaN
93301,I19,08/11/2023,November,2023,Anonim,KB.23.0029,2000000.0,SP,Cash on Hand,Institusi,Aktif,11,Aktif
93302,3841,09/11/2023,November,2023,Anonim,BSI602.23.0070,50000.0,LAIN-LAIN,BSI 602,Umum,tetap,11,tetap
93303,2930,01/01/2024,Januari,2024,Nany Maryani,BCA446.23.0225,50000.0,LIBURAN,BCA 446,Umum,NaN,NaN,tetap
93304,,02/02/2024,Februari,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN
93305,,03/03/2024,Maret,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN
93306,,04/04/2024,April,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN
93307,,05/05/2024,Mei,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN
93308,,06/06/2024,Juni,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN
93309,,07/07/2024,Juli,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN
93310,,08/08/2024,Agustus,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN
93311,,09/09/2024,September,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN
93312,,10/10/2024,Oktober,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN
93313,,11/11/2024,November,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN
93314,,12/12/2024,Desember,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,NaN,NaN,NaN

In [ ]:
merge_data['STATUS_y'] = merge_data['STATUS_y'].fillna('Lain-Lain')

In [ ]:
master_data['STATUS'] = merge_data['STATUS_y']
master_data.tail(15)

,KODE_DONATUR,TANGGAL,BULAN,TAHUN,NAMA_DONATUR,NO_REFF,DEBET,KETERANGAN,NAMA_BANK,BASE_DONATUR,STATUS,BULAN_NO
93300,nan,06/11/2023,November,2023,Anonim,BSI572.23.0018,174600000.0,INFAQ,BSI 572,Donatur Baru,Lain-Lain,11
93301,I19,08/11/2023,November,2023,Anonim,KB.23.0029,2000000.0,SP,Cash on Hand,Institusi,Aktif,11
93302,3841,09/11/2023,November,2023,Anonim,BSI602.23.0070,50000.0,LAIN-LAIN,BSI 602,Umum,tetap,11
93303,2930,01/01/2024,Januari,2024,Nany Maryani,BCA446.23.0225,50000.0,LIBURAN,BCA 446,Umum,tetap,NaN
93304,,02/02/2024,Februari,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN
93305,,03/03/2024,Maret,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN
93306,,04/04/2024,April,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN
93307,,05/05/2024,Mei,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN
93308,,06/06/2024,Juni,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN
93309,,07/07/2024,Juli,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN
93310,,08/08/2024,Agustus,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN
93311,,09/09/2024,September,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN
93312,,10/10/2024,Oktober,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN
93313,,11/11/2024,November,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN
93314,,12/12/2024,Desember,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,NaN

In [ ]:
master_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93315 entries, 0 to 93314
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   KODE_DONATUR  93315 non-null  object
 1   TANGGAL       92233 non-null  object
 2   BULAN         93315 non-null  object
 3   TAHUN         93315 non-null  object
 4   NAMA_DONATUR  93315 non-null  object
 5   NO_REFF       93315 non-null  object
 6   DEBET         93315 non-null  float64
 7   KETERANGAN    93315 non-null  object
 8   NAMA_BANK     93315 non-null  object
 9   BASE_DONATUR  93315 non-null  object
 10  STATUS        93315 non-null  object
 11  BULAN_NO      93303 non-null  object
dtypes: float64(1), object(11)
memory usage: 8.5+ MB

In [ ]:
master_data['TANGGAL'] = pd.to_datetime(master_data['TANGGAL'], format='%d/%m/%Y', errors='coerce')
master_data['BULAN_NO'] = master_data['TANGGAL'].dt.month

In [ ]:
master_data = master_data.reset_index(drop='first')

In [ ]:
control_p = master_data.pivot_table(index=['BULAN','KETERANGAN'], columns='BULAN_NO', values='DEBET', aggfunc={'DEBET': ['count', 'sum']})
control_p.tail(15)

                       count                                             \
BULAN_NO                1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0     9.0
BULAN     KETERANGAN
Oktober   INSTITUSI      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN
          LAIN-LAIN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN
          PROPHETICA     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN
          SP             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN
          WAKAF ASRAMA   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN
          WAPRO          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN
          ZAKAT          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     NaN
September INFAQ          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  3212.0
          INSTITUSI      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     9.0
          LAIN-LAIN      NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   230.0
          PROPHETICA     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN     4.0
          SP             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   783.0
          WAKAF ASRAMA   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   187.0
          WAPRO          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   108.0
          ZAKAT          NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  2255.0

                                ...  sum                           \
BULAN_NO                  10.0  ... 3.0  4.0  5.0  6.0  7.0  8.0
BULAN     KETERANGAN            ...
Oktober   INSTITUSI       10.0  ...  NaN  NaN  NaN  NaN  NaN  NaN
          LAIN-LAIN      372.0  ...  NaN  NaN  NaN  NaN  NaN  NaN
          PROPHETICA       2.0  ...  NaN  NaN  NaN  NaN  NaN  NaN
          SP             871.0  ...  NaN  NaN  NaN  NaN  NaN  NaN
          WAKAF ASRAMA   159.0  ...  NaN  NaN  NaN  NaN  NaN  NaN
          WAPRO           61.0  ...  NaN  NaN  NaN  NaN  NaN  NaN
          ZAKAT         2023.0  ...  NaN  NaN  NaN  NaN  NaN  NaN
September INFAQ            NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
          INSTITUSI        NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
          LAIN-LAIN        NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
          PROPHETICA       NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
          SP               NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
          WAKAF ASRAMA     NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
          WAPRO            NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
          ZAKAT            NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN


BULAN_NO                        9.0          10.0 11.0 12.0
BULAN     KETERANGAN
Oktober   INSTITUSI              NaN  297000000.0  NaN  NaN
          LAIN-LAIN              NaN  625111992.0  NaN  NaN
          PROPHETICA             NaN     160000.0  NaN  NaN
          SP                     NaN  326754876.0  NaN  NaN
          WAKAF ASRAMA           NaN   36619995.0  NaN  NaN
          WAPRO                  NaN  209350211.0  NaN  NaN
          ZAKAT                  NaN  351790872.0  NaN  NaN
September INFAQ         2.988157e+08          NaN  NaN  NaN
          INSTITUSI     2.650000e+08          NaN  NaN  NaN
          LAIN-LAIN     6.083019e+08          NaN  NaN  NaN
          PROPHETICA    9.100000e+05          NaN  NaN  NaN
          SP            3.434181e+08          NaN  NaN  NaN
          WAKAF ASRAMA  5.147418e+07          NaN  NaN  NaN
          WAPRO         2.259050e+08          NaN  NaN  NaN
          ZAKAT         2.756767e+08          NaN  NaN  NaN

[15 rows x 24 columns]

In [ ]:
control_p.columns = ['_'.join(map(str, col)).strip() if col[1] else col[0] for col in control_p.columns]
control_p

                        count_1.0  count_2.0  count_3.0  count_4.0  count_5.0  \
BULAN     KETERANGAN
Agustus   INFAQ               NaN        NaN        NaN        NaN        NaN
          INSTITUSI           NaN        NaN        NaN        NaN        NaN
          LAIN-LAIN           NaN        NaN        NaN        NaN        NaN
          PROPHETICA          NaN        NaN        NaN        NaN        NaN
          SP                  NaN        NaN        NaN        NaN        NaN
...                           ...        ...        ...        ...        ...
September PROPHETICA          NaN        NaN        NaN        NaN        NaN
          SP                  NaN        NaN        NaN        NaN        NaN
          WAKAF ASRAMA        NaN        NaN        NaN        NaN        NaN
          WAPRO               NaN        NaN        NaN        NaN        NaN
          ZAKAT               NaN        NaN        NaN        NaN        NaN

                        count_6.0  count_7.0  count_8.0  count_9.0  \
BULAN     KETERANGAN
Agustus   INFAQ               NaN        NaN     3809.0        NaN
          INSTITUSI           NaN        NaN       11.0        NaN
          LAIN-LAIN           NaN        NaN      219.0        NaN
          PROPHETICA          NaN        NaN       15.0        NaN
          SP                  NaN        NaN      718.0        NaN
...                           ...        ...        ...        ...
September PROPHETICA          NaN        NaN        NaN        4.0
          SP                  NaN        NaN        NaN      783.0
          WAKAF ASRAMA        NaN        NaN        NaN      187.0
          WAPRO               NaN        NaN        NaN      108.0
          ZAKAT               NaN        NaN        NaN     2255.0

                        count_10.0  ...  sum_3.0  sum_4.0  sum_5.0  sum_6.0  \
BULAN     KETERANGAN                ...
Agustus   INFAQ                NaN  ...      NaN      NaN      NaN      NaN
          INSTITUSI            NaN  ...      NaN      NaN      NaN      NaN
          LAIN-LAIN            NaN  ...      NaN      NaN      NaN      NaN
          PROPHETICA           NaN  ...      NaN      NaN      NaN      NaN
          SP                   NaN  ...      NaN      NaN      NaN      NaN
...                            ...  ...      ...      ...      ...      ...
September PROPHETICA           NaN  ...      NaN      NaN      NaN      NaN
          SP                   NaN  ...      NaN      NaN      NaN      NaN
          WAKAF ASRAMA         NaN  ...      NaN      NaN      NaN      NaN
          WAPRO                NaN  ...      NaN      NaN      NaN      NaN
          ZAKAT                NaN  ...      NaN      NaN      NaN      NaN

                        sum_7.0       sum_8.0       sum_9.0  sum_10.0  \
BULAN     KETERANGAN
Agustus   INFAQ             NaN  3.796640e+08           NaN       NaN
          INSTITUSI         NaN  2.890000e+08           NaN       NaN
          LAIN-LAIN         NaN  1.314516e+09           NaN       NaN
          PROPHETICA        NaN  3.080000e+06           NaN       NaN
          SP                NaN  3.490508e+08           NaN       NaN
...                         ...           ...           ...       ...
September PROPHETICA        NaN           NaN  9.100000e+05       NaN
          SP                NaN           NaN  3.434181e+08       NaN
          WAKAF ASRAMA      NaN           NaN  5.147418e+07       NaN
          WAPRO             NaN           NaN  2.259050e+08       NaN
          ZAKAT             NaN           NaN  2.756767e+08       NaN

                        sum_11.0  sum_12.0
BULAN     KETERANGAN
Agustus   INFAQ              NaN       NaN
          INSTITUSI          NaN       NaN
          LAIN-LAIN          NaN       NaN
          PROPHETICA         NaN       NaN
          SP                 NaN       NaN
...                          ...       ...
September PROPHETICA         NaN       NaN
          SP                 NaN       NaN
          WAKAF ASRAMA       NaN       NaN
          WAPRO              NaN       NaN
          ZAKAT              NaN       NaN

[95 rows x 24 columns]

In [ ]:
control_p = control_p.reset_index()
control_p

,BULAN,KETERANGAN,count_1.0,count_2.0,count_3.0,count_4.0,count_5.0,count_6.0,count_7.0,count_8.0,...,sum_3.0,sum_4.0,sum_5.0,sum_6.0,sum_7.0,sum_8.0,sum_9.0,sum_10.0,sum_11.0,sum_12.0
0,Agustus,INFAQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3809.0,...,NaN,NaN,NaN,NaN,NaN,3.796640e+08,NaN,NaN,NaN,NaN
1,Agustus,INSTITUSI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,...,NaN,NaN,NaN,NaN,NaN,2.890000e+08,NaN,NaN,NaN,NaN
2,Agustus,LAIN-LAIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,219.0,...,NaN,NaN,NaN,NaN,NaN,1.314516e+09,NaN,NaN,NaN,NaN
3,Agustus,PROPHETICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,...,NaN,NaN,NaN,NaN,NaN,3.080000e+06,NaN,NaN,NaN,NaN
4,Agustus,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,718.0,...,NaN,NaN,NaN,NaN,NaN,3.490508e+08,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,September,PROPHETICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,9.100000e+05,NaN,NaN,NaN
91,September,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.434181e+08,NaN,NaN,NaN
92,September,WAKAF ASRAMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.147418e+07,NaN,NaN,NaN
93,September,WAPRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.259050e+08,NaN,NaN,NaN
94,September,ZAKAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.756767e+08,NaN,NaN,NaN

In [ ]:
control_p['cnt_donasi'] = control_p.iloc[:, 2:14].sum(axis=1)
control_p['Donation Rate'] = control_p.iloc[:, 2:14].sum(axis=1) / len(control_p.iloc[:, 2:14].columns)
control_p['Total Donation'] = control_p.iloc[:, 14:26].sum(axis=1)
control_p

,BULAN,KETERANGAN,count_1.0,count_2.0,count_3.0,count_4.0,count_5.0,count_6.0,count_7.0,count_8.0,...,sum_6.0,sum_7.0,sum_8.0,sum_9.0,sum_10.0,sum_11.0,sum_12.0,cnt_donasi,Donation Rate,Total Donation
0,Agustus,INFAQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3809.0,...,NaN,NaN,3.796640e+08,NaN,NaN,NaN,NaN,3809.0,317.416667,3.796640e+08
1,Agustus,INSTITUSI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.0,...,NaN,NaN,2.890000e+08,NaN,NaN,NaN,NaN,11.0,0.916667,2.890000e+08
2,Agustus,LAIN-LAIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,219.0,...,NaN,NaN,1.314516e+09,NaN,NaN,NaN,NaN,219.0,18.250000,1.314516e+09
3,Agustus,PROPHETICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,...,NaN,NaN,3.080000e+06,NaN,NaN,NaN,NaN,15.0,1.250000,3.080000e+06
4,Agustus,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,718.0,...,NaN,NaN,3.490508e+08,NaN,NaN,NaN,NaN,718.0,59.833333,3.490508e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,September,PROPHETICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,9.100000e+05,NaN,NaN,NaN,4.0,0.333333,9.100000e+05
91,September,SP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.434181e+08,NaN,NaN,NaN,783.0,65.250000,3.434181e+08
92,September,WAKAF ASRAMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.147418e+07,NaN,NaN,NaN,187.0,15.583333,5.147418e+07
93,September,WAPRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.259050e+08,NaN,NaN,NaN,108.0,9.000000,2.259050e+08
94,September,ZAKAT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.756767e+08,NaN,NaN,NaN,2255.0,187.916667,2.756767e+08

In [ ]:
control_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 29 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BULAN           95 non-null     object
 1   KETERANGAN      95 non-null     object
 2   count_1.0       9 non-null      float64
 3   count_2.0       7 non-null      float64
 4   count_3.0       8 non-null      float64
 5   count_4.0       8 non-null      float64
 6   count_5.0       8 non-null      float64
 7   count_6.0       8 non-null      float64
 8   count_7.0       8 non-null      float64
 9   count_8.0       8 non-null      float64
 10  count_9.0       8 non-null      float64
 11  count_10.0      8 non-null      float64
 12  count_11.0      8 non-null      float64
 13  count_12.0      7 non-null      float64
 14  sum_1.0         9 non-null      float64
 15  sum_2.0         7 non-null      float64
 16  sum_3.0         8 non-null      float64
 17  sum_4.0         8 non-null      float64
 18  sum_5.0         8 non-null      float64
 19  sum_6.0         8 non-null      float64
 20  sum_7.0         8 non-null      float64
 21  sum_8.0         8 non-null      float64
 22  sum_9.0         8 non-null      float64
 23  sum_10.0        8 non-null      float64
 24  sum_11.0        8 non-null      float64
 25  sum_12.0        7 non-null      float64
 26  cnt_donasi      95 non-null     float64
 27  Donation Rate   95 non-null     float64
 28  Total Donation  95 non-null     float64
dtypes: float64(27), object(2)
memory usage: 21.6+ KB

In [ ]:
control_product = control_p[['BULAN','KETERANGAN','cnt_donasi','Donation Rate','Total Donation']]
control_product

        BULAN    KETERANGAN  cnt_donasi  Donation Rate  Total Donation
0     Agustus         INFAQ      3809.0     317.416667    3.796640e+08
1     Agustus     INSTITUSI        11.0       0.916667    2.890000e+08
2     Agustus     LAIN-LAIN       219.0      18.250000    1.314516e+09
3     Agustus    PROPHETICA        15.0       1.250000    3.080000e+06
4     Agustus            SP       718.0      59.833333    3.490508e+08
..        ...           ...         ...            ...             ...
90  September    PROPHETICA         4.0       0.333333    9.100000e+05
91  September            SP       783.0      65.250000    3.434181e+08
92  September  WAKAF ASRAMA       187.0      15.583333    5.147418e+07
93  September         WAPRO       108.0       9.000000    2.259050e+08
94  September         ZAKAT      2255.0     187.916667    2.756767e+08

[95 rows x 5 columns]

In [ ]:
control_s = master_data.pivot_table(index=['BULAN','BASE_DONATUR'], columns='BULAN_NO', values='DEBET', aggfunc=['count','sum'])
control_s.head(20)

                      count                                                \
BULAN_NO               1.0  2.0  3.0     4.0  5.0  6.0  7.0     8.0  9.0
BULAN    BASE_DONATUR
Agustus  Alumni         NaN  NaN  NaN     NaN  NaN  NaN  NaN  1290.0  NaN
         Donatur Baru   NaN  NaN  NaN     NaN  NaN  NaN  NaN  5633.0  NaN
         Institusi      NaN  NaN  NaN     NaN  NaN  NaN  NaN    25.0  NaN
         Lain-Lain      NaN  NaN  NaN     NaN  NaN  NaN  NaN    77.0  NaN
         Orang Tua      NaN  NaN  NaN     NaN  NaN  NaN  NaN    25.0  NaN
         Pembina        NaN  NaN  NaN     NaN  NaN  NaN  NaN    15.0  NaN
         Umum           NaN  NaN  NaN     NaN  NaN  NaN  NaN   275.0  NaN
April    Alumni         NaN  NaN  NaN  2433.0  NaN  NaN  NaN     NaN  NaN
         Donatur Baru   NaN  NaN  NaN  5667.0  NaN  NaN  NaN     NaN  NaN
         Institusi      NaN  NaN  NaN    25.0  NaN  NaN  NaN     NaN  NaN
         Lain-Lain      NaN  NaN  NaN   162.0  NaN  NaN  NaN     NaN  NaN
         Orang Tua      NaN  NaN  NaN    35.0  NaN  NaN  NaN     NaN  NaN
         Pembina        NaN  NaN  NaN    28.0  NaN  NaN  NaN     NaN  NaN
         Umum           NaN  NaN  NaN  1027.0  NaN  NaN  NaN     NaN  NaN
Desember Alumni         NaN  NaN  NaN     NaN  NaN  NaN  NaN     NaN  NaN
         Donatur Baru   NaN  NaN  NaN     NaN  NaN  NaN  NaN     NaN  NaN
         Institusi      NaN  NaN  NaN     NaN  NaN  NaN  NaN     NaN  NaN
         Lain-Lain      NaN  NaN  NaN     NaN  NaN  NaN  NaN     NaN  NaN
         Orang Tua      NaN  NaN  NaN     NaN  NaN  NaN  NaN     NaN  NaN
         Pembina        NaN  NaN  NaN     NaN  NaN  NaN  NaN     NaN  NaN

                            ...  sum                               \
BULAN_NO              10.0  ... 3.0           4.0  5.0  6.0  7.0
BULAN    BASE_DONATUR       ...
Agustus  Alumni        NaN  ...  NaN           NaN  NaN  NaN  NaN
         Donatur Baru  NaN  ...  NaN           NaN  NaN  NaN  NaN
         Institusi     NaN  ...  NaN           NaN  NaN  NaN  NaN
         Lain-Lain     NaN  ...  NaN           NaN  NaN  NaN  NaN
         Orang Tua     NaN  ...  NaN           NaN  NaN  NaN  NaN
         Pembina       NaN  ...  NaN           NaN  NaN  NaN  NaN
         Umum          NaN  ...  NaN           NaN  NaN  NaN  NaN
April    Alumni        NaN  ...  NaN  9.026612e+08  NaN  NaN  NaN
         Donatur Baru  NaN  ...  NaN  9.993168e+08  NaN  NaN  NaN
         Institusi     NaN  ...  NaN  8.195830e+08  NaN  NaN  NaN
         Lain-Lain     NaN  ...  NaN  5.396682e+07  NaN  NaN  NaN
         Orang Tua     NaN  ...  NaN  1.800034e+07  NaN  NaN  NaN
         Pembina       NaN  ...  NaN  2.518798e+08  NaN  NaN  NaN
         Umum          NaN  ...  NaN  2.802986e+08  NaN  NaN  NaN
Desember Alumni        NaN  ...  NaN           NaN  NaN  NaN  NaN
         Donatur Baru  NaN  ...  NaN           NaN  NaN  NaN  NaN
         Institusi     NaN  ...  NaN           NaN  NaN  NaN  NaN
         Lain-Lain     NaN  ...  NaN           NaN  NaN  NaN  NaN
         Orang Tua     NaN  ...  NaN           NaN  NaN  NaN  NaN
         Pembina       NaN  ...  NaN           NaN  NaN  NaN  NaN


BULAN_NO                       8.0  9.0  10.0 11.0          12.0
BULAN    BASE_DONATUR
Agustus  Alumni        3.356380e+08  NaN  NaN  NaN           NaN
         Donatur Baru  1.665575e+09  NaN  NaN  NaN           NaN
         Institusi     6.157995e+08  NaN  NaN  NaN           NaN
         Lain-Lain     9.416663e+07  NaN  NaN  NaN           NaN
         Orang Tua     8.070884e+06  NaN  NaN  NaN           NaN
         Pembina       6.040828e+07  NaN  NaN  NaN           NaN
         Umum          1.160555e+08  NaN  NaN  NaN           NaN
April    Alumni                 NaN  NaN  NaN  NaN           NaN
         Donatur Baru           NaN  NaN  NaN  NaN           NaN
         Institusi              NaN  NaN  NaN  NaN           NaN
         Lain-Lain              NaN  NaN  NaN  NaN           NaN
         Orang Tua              NaN  NaN  NaN  NaN           NaN
         Pembina                NaN  NaN  NaN  NaN           NaN
         Umum                   NaN  NaN  NaN  NaN           NaN
Desember Alumni                 NaN  NaN  NaN  NaN  2.662072e+08
         Donatur Baru           NaN  NaN  NaN  NaN  4.645692e+08
         Institusi              NaN  NaN  NaN  NaN  5.808672e+08
         Lain-Lain              NaN  NaN  NaN  NaN  4.650000e+06
         Orang Tua              NaN  NaN  NaN  NaN  2.010057e+07
         Pembina                NaN  NaN  NaN  NaN  1.820020e+07

[20 rows x 24 columns]

In [ ]:
control_s.columns = ['_'.join(map(str, col)).strip() if col[1] else col[0] for col in control_s.columns]
control_s

                        count_1.0  count_2.0  count_3.0  count_4.0  count_5.0  \
BULAN     BASE_DONATUR
Agustus   Alumni              NaN        NaN        NaN        NaN        NaN
          Donatur Baru        NaN        NaN        NaN        NaN        NaN
          Institusi           NaN        NaN        NaN        NaN        NaN
          Lain-Lain           NaN        NaN        NaN        NaN        NaN
          Orang Tua           NaN        NaN        NaN        NaN        NaN
...                           ...        ...        ...        ...        ...
September Institusi           NaN        NaN        NaN        NaN        NaN
          Lain-Lain           NaN        NaN        NaN        NaN        NaN
          Orang Tua           NaN        NaN        NaN        NaN        NaN
          Pembina             NaN        NaN        NaN        NaN        NaN
          Umum                NaN        NaN        NaN        NaN        NaN

                        count_6.0  count_7.0  count_8.0  count_9.0  \
BULAN     BASE_DONATUR
Agustus   Alumni              NaN        NaN     1290.0        NaN
          Donatur Baru        NaN        NaN     5633.0        NaN
          Institusi           NaN        NaN       25.0        NaN
          Lain-Lain           NaN        NaN       77.0        NaN
          Orang Tua           NaN        NaN       25.0        NaN
...                           ...        ...        ...        ...
September Institusi           NaN        NaN        NaN       24.0
          Lain-Lain           NaN        NaN        NaN       52.0
          Orang Tua           NaN        NaN        NaN       31.0
          Pembina             NaN        NaN        NaN       15.0
          Umum                NaN        NaN        NaN      368.0

                        count_10.0  ...  sum_3.0  sum_4.0  sum_5.0  sum_6.0  \
BULAN     BASE_DONATUR              ...
Agustus   Alumni               NaN  ...      NaN      NaN      NaN      NaN
          Donatur Baru         NaN  ...      NaN      NaN      NaN      NaN
          Institusi            NaN  ...      NaN      NaN      NaN      NaN
          Lain-Lain            NaN  ...      NaN      NaN      NaN      NaN
          Orang Tua            NaN  ...      NaN      NaN      NaN      NaN
...                            ...  ...      ...      ...      ...      ...
September Institusi            NaN  ...      NaN      NaN      NaN      NaN
          Lain-Lain            NaN  ...      NaN      NaN      NaN      NaN
          Orang Tua            NaN  ...      NaN      NaN      NaN      NaN
          Pembina              NaN  ...      NaN      NaN      NaN      NaN
          Umum                 NaN  ...      NaN      NaN      NaN      NaN

                        sum_7.0       sum_8.0      sum_9.0  sum_10.0  \
BULAN     BASE_DONATUR
Agustus   Alumni            NaN  3.356380e+08          NaN       NaN
          Donatur Baru      NaN  1.665575e+09          NaN       NaN
          Institusi         NaN  6.157995e+08          NaN       NaN
          Lain-Lain         NaN  9.416663e+07          NaN       NaN
          Orang Tua         NaN  8.070884e+06          NaN       NaN
...                         ...           ...          ...       ...
September Institusi         NaN           NaN  403683000.0       NaN
          Lain-Lain         NaN           NaN   26837119.0       NaN
          Orang Tua         NaN           NaN   14225394.0       NaN
          Pembina           NaN           NaN  132000051.0       NaN
          Umum              NaN           NaN   97531589.0       NaN

                        sum_11.0  sum_12.0
BULAN     BASE_DONATUR
Agustus   Alumni             NaN       NaN
          Donatur Baru       NaN       NaN
          Institusi          NaN       NaN
          Lain-Lain          NaN       NaN
          Orang Tua          NaN       NaN
...                          ...       ...
September Institusi          NaN       NaN
          Lain-Lain          NaN       NaN
          Orang Tua          NaN       NaN
          Pembina            NaN       NaN
          Umum               NaN       NaN

[84 rows x 24 columns]

In [ ]:
control_s = control_s.reset_index()
control_s

,BULAN,BASE_DONATUR,count_1.0,count_2.0,count_3.0,count_4.0,count_5.0,count_6.0,count_7.0,count_8.0,...,sum_3.0,sum_4.0,sum_5.0,sum_6.0,sum_7.0,sum_8.0,sum_9.0,sum_10.0,sum_11.0,sum_12.0
0,Agustus,Alumni,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1290.0,...,NaN,NaN,NaN,NaN,NaN,3.356380e+08,NaN,NaN,NaN,NaN
1,Agustus,Donatur Baru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5633.0,...,NaN,NaN,NaN,NaN,NaN,1.665575e+09,NaN,NaN,NaN,NaN
2,Agustus,Institusi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,...,NaN,NaN,NaN,NaN,NaN,6.157995e+08,NaN,NaN,NaN,NaN
3,Agustus,Lain-Lain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,...,NaN,NaN,NaN,NaN,NaN,9.416663e+07,NaN,NaN,NaN,NaN
4,Agustus,Orang Tua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,...,NaN,NaN,NaN,NaN,NaN,8.070884e+06,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,September,Institusi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,403683000.0,NaN,NaN,NaN
80,September,Lain-Lain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,26837119.0,NaN,NaN,NaN
81,September,Orang Tua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,14225394.0,NaN,NaN,NaN
82,September,Pembina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,132000051.0,NaN,NaN,NaN
83,September,Umum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,97531589.0,NaN,NaN,NaN

In [ ]:
control_s['cnt_donasi'] = control_s.iloc[:, 2:14].sum(axis=1)
control_s['Donation Rate'] = control_s.iloc[:, 2:14].sum(axis=1) / len(control_s.iloc[:, 2:14].columns)
control_s['Total Donation'] = control_s.iloc[:, 14:26].sum(axis=1)
control_s

,BULAN,BASE_DONATUR,count_1.0,count_2.0,count_3.0,count_4.0,count_5.0,count_6.0,count_7.0,count_8.0,...,sum_6.0,sum_7.0,sum_8.0,sum_9.0,sum_10.0,sum_11.0,sum_12.0,cnt_donasi,Donation Rate,Total Donation
0,Agustus,Alumni,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1290.0,...,NaN,NaN,3.356380e+08,NaN,NaN,NaN,NaN,1290.0,107.500000,3.356380e+08
1,Agustus,Donatur Baru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5633.0,...,NaN,NaN,1.665575e+09,NaN,NaN,NaN,NaN,5633.0,469.416667,1.665575e+09
2,Agustus,Institusi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,...,NaN,NaN,6.157995e+08,NaN,NaN,NaN,NaN,25.0,2.083333,6.157995e+08
3,Agustus,Lain-Lain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.0,...,NaN,NaN,9.416663e+07,NaN,NaN,NaN,NaN,77.0,6.416667,9.416663e+07
4,Agustus,Orang Tua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,...,NaN,NaN,8.070884e+06,NaN,NaN,NaN,NaN,25.0,2.083333,8.070884e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,September,Institusi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,403683000.0,NaN,NaN,NaN,24.0,2.000000,4.036830e+08
80,September,Lain-Lain,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,26837119.0,NaN,NaN,NaN,52.0,4.333333,2.683712e+07
81,September,Orang Tua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,14225394.0,NaN,NaN,NaN,31.0,2.583333,1.422539e+07
82,September,Pembina,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,132000051.0,NaN,NaN,NaN,15.0,1.250000,1.320001e+08
83,September,Umum,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,97531589.0,NaN,NaN,NaN,368.0,30.666667,9.753159e+07

In [ ]:
control_segment = control_s[['BULAN','BASE_DONATUR','cnt_donasi','Donation Rate','Total Donation']]
control_segment

        BULAN  BASE_DONATUR  cnt_donasi  Donation Rate  Total Donation
0     Agustus        Alumni      1290.0     107.500000    3.356380e+08
1     Agustus  Donatur Baru      5633.0     469.416667    1.665575e+09
2     Agustus     Institusi        25.0       2.083333    6.157995e+08
3     Agustus     Lain-Lain        77.0       6.416667    9.416663e+07
4     Agustus     Orang Tua        25.0       2.083333    8.070884e+06
..        ...           ...         ...            ...             ...
79  September     Institusi        24.0       2.000000    4.036830e+08
80  September     Lain-Lain        52.0       4.333333    2.683712e+07
81  September     Orang Tua        31.0       2.583333    1.422539e+07
82  September       Pembina        15.0       1.250000    1.320001e+08
83  September          Umum       368.0      30.666667    9.753159e+07

[84 rows x 5 columns]

In [ ]:
master_data.columns

Index(['KODE_DONATUR', 'TANGGAL', 'BULAN', 'TAHUN', 'NAMA_DONATUR', 'NO_REFF',
       'DEBET', 'KETERANGAN', 'NAMA_BANK', 'BASE_DONATUR', 'STATUS',
       'BULAN_NO'],
      dtype='object')

In [ ]:
master_data.tail(30)

,KODE_DONATUR,TANGGAL,BULAN,TAHUN,NAMA_DONATUR,NO_REFF,DEBET,KETERANGAN,NAMA_BANK,BASE_DONATUR,STATUS,BULAN_NO
93285,4038,2023-11-03,November,2023,Anonim,NIASR1.23.0401,420000.0,LAIN-LAIN,CIMB R1,Umum,tetap,11.0
93286,1254,2023-11-05,November,2023,Anonim,NIASR1.23.0402,10000.0,WAKAF ASRAMA,CIMB R1,Alumni,tetap,11.0
93287,4038,2023-11-05,November,2023,Anonim,NIASR1.23.0403,300000.0,LAIN-LAIN,CIMB R1,Umum,tetap,11.0
93288,1254,2023-11-07,November,2023,Anonim,NIASR1.23.0404,10000.0,WAKAF ASRAMA,CIMB R1,Alumni,tetap,11.0
93289,4038,2023-11-10,November,2023,Anonim,NIASR1.23.0405,100000.0,LAIN-LAIN,CIMB R1,Umum,tetap,11.0
93290,1254,2023-11-12,November,2023,Anonim,NIASR1.23.0406,10000.0,WAKAF ASRAMA,CIMB R1,Alumni,tetap,11.0
93291,405,2023-11-12,November,2023,Anonim,NIASR1.23.0407,800000.0,SP,CIMB R1,Alumni,prioritas,11.0
93292,794,2023-11-06,November,2023,Anonim,NIASR2.23.0127,100000.0,SP,CIMB R2,Alumni,tetap,11.0
93293,828,2023-11-06,November,2023,Anonim,NIASR2.23.0127,100000.0,SP,CIMB R2,Alumni,tetap,11.0
93294,818,2023-11-06,November,2023,Anonim,NIASR2.23.0127,100000.0,SP,CIMB R2,Alumni,tetap,11.0
93295,801,2023-11-06,November,2023,Anonim,NIASR2.23.0127,100000.0,SP,CIMB R2,Alumni,tetap,11.0
93296,809,2023-11-06,November,2023,Anonim,NIASR2.23.0127,100000.0,SP,CIMB R2,Alumni,tetap,11.0
93297,259,2023-11-01,November,2023,Anonim,NIASR6.23.0106,500000.0,SP,CIMB R6,Alumni,tetap,11.0
93298,2424,2023-11-02,November,2023,Anonim,NIASR6.23.0107,500000.0,SP,CIMB R6,Umum,tetap,11.0
93299,2424,2023-11-02,November,2023,Anonim,NIASR6.23.0108,38000.0,SP,CIMB R6,Umum,tetap,11.0
93300,nan,2023-11-06,November,2023,Anonim,BSI572.23.0018,174600000.0,INFAQ,BSI 572,Donatur Baru,Lain-Lain,11.0
93301,I19,2023-11-08,November,2023,Anonim,KB.23.0029,2000000.0,SP,Cash on Hand,Institusi,Aktif,11.0
93302,3841,2023-11-09,November,2023,Anonim,BSI602.23.0070,50000.0,LAIN-LAIN,BSI 602,Umum,tetap,11.0
93303,2930,2024-01-01,Januari,2024,Nany Maryani,BCA446.23.0225,50000.0,LIBURAN,BCA 446,Umum,tetap,1.0
93304,,2024-02-02,Februari,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,2.0
93305,,2024-03-03,Maret,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,3.0
93306,,2024-04-04,April,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,4.0
93307,,2024-05-05,Mei,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,5.0
93308,,2024-06-06,Juni,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,6.0
93309,,2024-07-07,Juli,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,7.0
93310,,2024-08-08,Agustus,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,8.0
93311,,2024-09-09,September,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,9.0
93312,,2024-10-10,Oktober,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,10.0
93313,,2024-11-11,November,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,11.0
93314,,2024-12-12,Desember,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,12.0

In [ ]:
master_data = master_data.reset_index(drop='first')

In [ ]:
from gspread_dataframe import set_with_dataframe

In [ ]:
master_data = master_data.drop_duplicates()
df_individu = df_individu.drop_duplicates()
df_non_individu = df_non_individu.drop_duplicates()
control_product = control_product.drop_duplicates()
control_segment = control_segment.drop_duplicates()

In [ ]:
master_data.tail(25)

,KODE_DONATUR,TANGGAL,BULAN,TAHUN,NAMA_DONATUR,NO_REFF,DEBET,KETERANGAN,NAMA_BANK,BASE_DONATUR,STATUS,BULAN_NO
93290,1254,2023-11-12,November,2023,Anonim,NIASR1.23.0406,10000.0,WAKAF ASRAMA,CIMB R1,Alumni,tetap,11.0
93291,405,2023-11-12,November,2023,Anonim,NIASR1.23.0407,800000.0,SP,CIMB R1,Alumni,prioritas,11.0
93292,794,2023-11-06,November,2023,Anonim,NIASR2.23.0127,100000.0,SP,CIMB R2,Alumni,tetap,11.0
93293,828,2023-11-06,November,2023,Anonim,NIASR2.23.0127,100000.0,SP,CIMB R2,Alumni,tetap,11.0
93294,818,2023-11-06,November,2023,Anonim,NIASR2.23.0127,100000.0,SP,CIMB R2,Alumni,tetap,11.0
93295,801,2023-11-06,November,2023,Anonim,NIASR2.23.0127,100000.0,SP,CIMB R2,Alumni,tetap,11.0
93296,809,2023-11-06,November,2023,Anonim,NIASR2.23.0127,100000.0,SP,CIMB R2,Alumni,tetap,11.0
93297,259,2023-11-01,November,2023,Anonim,NIASR6.23.0106,500000.0,SP,CIMB R6,Alumni,tetap,11.0
93298,2424,2023-11-02,November,2023,Anonim,NIASR6.23.0107,500000.0,SP,CIMB R6,Umum,tetap,11.0
93299,2424,2023-11-02,November,2023,Anonim,NIASR6.23.0108,38000.0,SP,CIMB R6,Umum,tetap,11.0
93300,nan,2023-11-06,November,2023,Anonim,BSI572.23.0018,174600000.0,INFAQ,BSI 572,Donatur Baru,Lain-Lain,11.0
93301,I19,2023-11-08,November,2023,Anonim,KB.23.0029,2000000.0,SP,Cash on Hand,Institusi,Aktif,11.0
93302,3841,2023-11-09,November,2023,Anonim,BSI602.23.0070,50000.0,LAIN-LAIN,BSI 602,Umum,tetap,11.0
93303,2930,2024-01-01,Januari,2024,Nany Maryani,BCA446.23.0225,50000.0,LIBURAN,BCA 446,Umum,tetap,1.0
93304,,2024-02-02,Februari,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,2.0
93305,,2024-03-03,Maret,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,3.0
93306,,2024-04-04,April,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,4.0
93307,,2024-05-05,Mei,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,5.0
93308,,2024-06-06,Juni,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,6.0
93309,,2024-07-07,Juli,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,7.0
93310,,2024-08-08,Agustus,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,8.0
93311,,2024-09-09,September,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,9.0
93312,,2024-10-10,Oktober,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,10.0
93313,,2024-11-11,November,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,11.0
93314,,2024-12-12,Desember,2024,Anonim,BCA446.23.0244,1.0,ZAKAT,BCA 446,Donatur Baru,Lain-Lain,12.0

In [ ]:
master_data.duplicated().sum()

0

In [ ]:
master.clear()
con_individu.clear()
con_nonindividu.clear()
con_produk.clear()
con_segment.clear()

{'spreadsheetId': '1nyNdQmTsSlEzu08a8R7PqPFGTSslDbs8Fc_cVz0sb-A',
 'clearedRange': "'CONTROL SEGMENT.'!A1:Z1000"}

In [ ]:
set_with_dataframe(master, master_data, include_index=False, include_column_header=True)
set_with_dataframe(con_individu, df_individu, include_index=False, include_column_header=True)
set_with_dataframe(con_nonindividu, df_non_individu, include_index=False, include_column_header=True)
set_with_dataframe(con_produk, control_product, include_index=False, include_column_header=True)
set_with_dataframe(con_segment, control_segment, include_index=False, include_column_header=True)